In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'Your videos are good'
      ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'Your videos are good']

In [4]:
#DEefine vocabulary size
voc_size=10000

In [5]:
#One hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[2325, 4508, 9249, 5125],
 [2325, 4508, 9249, 8828],
 [2325, 3019, 9249, 670],
 [93, 7059, 4662, 3660, 1726],
 [93, 7059, 4662, 3660, 5034],
 [8822, 2325, 9263, 9249, 6974],
 [8726, 9386, 3629, 3660]]

In [39]:
# Word embedding representation

from tensorflow.keras.layers import Embedding,Dense,Input,Flatten
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [15]:
import numpy as np

In [16]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2325 4508 9249 5125]
 [   0    0    0    0 2325 4508 9249 8828]
 [   0    0    0    0 2325 3019 9249  670]
 [   0    0    0   93 7059 4662 3660 1726]
 [   0    0    0   93 7059 4662 3660 5034]
 [   0    0    0 8822 2325 9263 9249 6974]
 [   0    0    0    0 8726 9386 3629 3660]]


In [10]:
#Feature Representation
dim=10


In [43]:
model=Sequential()
model.add(Input(shape=(sent_length,1)))
model.add(Embedding(input_dim=voc_size, output_dim=dim))
# model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [44]:
model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ (None, 8, 1, 10)       │       100,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 8, 1, 1)        │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,011 (390.67 KB)

 Trainable params: 100,011 (390.67 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[[[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.49574178]],

        [[0.48706076]],

        [[0.49763662]],

        [[0.5064447 ]]],


       [[[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.49574178]],

        [[0.48706076]],

        [[0.49763662]],

        [[0.49894646]]],


       [[[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.49574178]],

        [[0.504617  ]],

        [[0.49763662]],

        [[0.49556816]]],


       [[[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.49137592]],

        [[0.496998  ]],

        [[0.4938991 ]],

        [[0.50158465]],

        [[0.5202023 ]]],


       [[[0.5032145 ]],

        [[0.5032145 ]],

        [[0.5032145 ]],

        [[0.49137592]],

        [[0.496998  ]],

        [[0.4938991 ]],

        [[0.50158465]],

        [[0.50315